#!/bin/bash

# Do not edit this file!

echo "Loading startup.sh..."
bash /home/startup.sh

# This script downloads the bot script, edits the config file and starts the bot:
mkdir -vv -p /home/remoteTelegramShell/
cd /home/remoteTelegramShell/

echo "Downloading Script telegramShellBot.py..."
wget https://raw.githubusercontent.com/EnriqueMoran/remoteTelegramShell/master/telegramShellBot.py \
     https://raw.githubusercontent.com/EnriqueMoran/remoteTelegramShell/master/config.txt && \
echo "Done." || echo "ERROR: Task Failed!"

echo "Editing config with given vars..."
sed -i \
-e "s/token = /token = $BOT_TOKEN/" \
-e "s/password = /password = $PASSWD/" \
-e "s/.\/shareFolder\//\/home\/remoteTelegramShell\/shareFolder\//" \
-e "s/.\/users.txt/\/home\/remoteTelegramShell\/users.txt/" \
-e "s/.\/log.txt/\/home\/remoteTelegramShell\/logs.txt/" \
-e "s/logLimit = 500/logLimit = $LOG_LIMIT/" \
-e "s/root = False/root = $ROOT/" config.txt && \
echo "Done." || echo "ERROR: Task Failed!"

echo "Starting Bot..."
python3 telegramShellBot.py
